apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: todo

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo
  name: todo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: hectoroftroy/k8s-gitops:1.9
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000