apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: kustomize.895570096d084edebbdc.westus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: todo
          servicePort: 3000
        path: /